//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Credits
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        public int Id { get; set; }
        public string OwnerName { get; set; }
        public int Summary { get; set; }
        public System.DateTime GivenDate { get; set; }
        public int Owner_Id { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
