//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Credits
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BankDbEntities : DbContext
    {
        public BankDbEntities()
            : base("name=BankDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Card> Cards { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<udv_showtotalsummary> udv_showtotalsummary { get; set; }
    
        public virtual int usp_AddCustomers(string name, string surname, Nullable<int> pasnumber)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var surnameParameter = surname != null ?
                new ObjectParameter("surname", surname) :
                new ObjectParameter("surname", typeof(string));
    
            var pasnumberParameter = pasnumber.HasValue ?
                new ObjectParameter("pasnumber", pasnumber) :
                new ObjectParameter("pasnumber", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_AddCustomers", nameParameter, surnameParameter, pasnumberParameter);
        }
    
        public virtual int usp_Givecredit(string name, Nullable<int> sum, Nullable<System.DateTime> datetimes, Nullable<int> ownerid)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var sumParameter = sum.HasValue ?
                new ObjectParameter("sum", sum) :
                new ObjectParameter("sum", typeof(int));
    
            var datetimesParameter = datetimes.HasValue ?
                new ObjectParameter("datetimes", datetimes) :
                new ObjectParameter("datetimes", typeof(System.DateTime));
    
            var owneridParameter = ownerid.HasValue ?
                new ObjectParameter("ownerid", ownerid) :
                new ObjectParameter("ownerid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_Givecredit", nameParameter, sumParameter, datetimesParameter, owneridParameter);
        }
    }
}
